from src.modules import *

commandName = os.path.basename(__file__).replace('.py', '')

def default(args=None, flags=None):
    message = f'--- PASTEL SESSION LOG ---\n'
    message += f'SessionID : {env.session.id}\n'
    message += f'Timestamp : {env.session.datetime}\n'
    message += f'--------------------------\n'

    if env.session.variables != {}:
        message += '\n[VARIABLES]\n'
        for k, v in env.session.variables.items():
            message += f"  {k} = {v}\n"
    
    if env.session.logs:
        message += '\n[COMMAND_HISTORY]\n'
        cmdNum = 1
        for i, cmd in enumerate(env.session.logs):
            if not cmd.strip().startswith('@'):
                message += f"  [{cmdNum:03d}] {cmd}\n"
                cmdNum += 1
    else:
        message += '\n- No commands executed in this session.\n'

    message += f'\n--- END OF LOG ---\n'
    message += f'\nGenerated by Pastel {env.getCommitHash()}.'

    if '-newfile' in flags:
        with open(os.path.join(Prompt.instance.shellCwd, 'logs_' + ''.join(random.choices(string.ascii_letters + string.digits, k=8)) + '.log'), 'w') as logFile:
            logFile.write(message)

    return message