from src.modules import *

class CommandManifest:
    NAME = 'logs'
    DESCRIPTION = 'Returns the commands used previously in the current Pastel session.'
    ARGS = []
    FLAGS = []

    def execute(args=None, flags=None, stdin=None):
        message = f'--- PASTEL SESSION LOG ---\n'
        message += f'SessionID : {env.session.id}\n'
        message += f'Timestamp : {env.session.datetime}\n'
        message += f'--------------------------\n'

        if env.session.listVariables() != {}:
            message += '\n[VARIABLES]\n'
            for k, v in env.session.listVariables():
                message += f"  {k} = {v}\n"
        
        if env.session.logs:
            message += '\n[COMMAND HISTORY]\n'
            cmdNum = 1
            for i, cmd in enumerate(env.session.logs):
                if not cmd.strip().startswith('@'):
                    message += f"  [{cmdNum:03d}] {cmd}\n"
                    cmdNum += 1
        else:
            message += '\n- No commands executed in this session.\n'

        message += f'\n--- END OF LOG ---\n'
        message += f'\nGenerated by Pastel {env.getCommitHash()}.'

        return message